### ISSUE TITLE
Serving a binary file as octet-stream

### ISSUE THREAD

**Issue by havokentity** [Kaliumhexacyanoferrat/GenHTTP#320] opened 2022-10-12 06:42 UTC
Hi,

I want to create a REST API that serves a file as octet-stream but I keep getting some error.

![image](https://user-images.githubusercontent.com/1956037/195268607-849c5802-4c3d-48c4-bea4-9804ad4d0628.png)

Here's my code so far:
```
public class BookService
    {
        [ResourceMethod]
        public async ValueTask<IResponse?> RequestResponse(IRequest request, IHandler handler)
        {
            string filePath = "d:\\KUTE_ANIME_DESCRIPTION.OBJ";
            byte[] fileBytes = await File.ReadAllBytesAsync(filePath);
            var dataStream = new MemoryStream(fileBytes);


            return await request.Respond().
                Content(dataStream, (ulong)fileBytes.LongLength, checkSumProvider).Status(ResponseStatus.OK).
                Type(new FlexibleContentType(ContentType.ApplicationOctetStream)).BuildTask();
        }


        ValueTask<ulong?> checkSumProvider()
        {
            return new ValueTask<ulong?>(555);
        }
    }
```
   

Any help would be much appreciated. I don't know if this is how you'd go about reading a file and serving it as an octet-stream.

**Comment by Kaliumhexacyanoferrat** [comment] 2022-10-12 07:22
Actually, you should be able to just:

```
public class BookService
{

    [ResourceMethod]
    public Stream RequestResponse()
    {
        return File.OpenRead(@"D:\KUTE_ANIME_DESCRIPTION.OBJ");
    }

}
```

**Comment by havokentity** [comment] 2022-10-12 08:39
Thanks for the reply! 

This is awesome but unfortunately I still get this exception though the file transfer works.

![image](https://user-images.githubusercontent.com/1956037/195294032-e825f79e-ae7d-433e-8a42-0d226008c536.png)


Just ignore it and continue? The file is around 11 mb, it doesn't happen with very small files

**Comment by Kaliumhexacyanoferrat** [comment] 2022-10-12 09:23
What client do you use to access the service? Plain browser? Have to check the behaviour with large files ...

**Comment by havokentity** [comment] 2022-10-12 09:28
Yea just plain browser, using Edge browser right now. I tried it with a Unity application also, but this time the exception was smaller. 

![image](https://user-images.githubusercontent.com/1956037/195305551-6ddf9850-d59c-425a-9f03-84867564f6bf.png)

**Comment by Kaliumhexacyanoferrat** [comment] 2022-10-12 09:38
Hm, cannot reproduce the issue with this minimal example:

```
Host.Create()
    .Handler(ServiceResource.From<WS>())
    .Defaults()
    .Development()
    .Console()
    .Run();


class WS
{

    [ResourceMethod]
    public Stream GetResult()
    {
        return File.OpenRead(@"C:\temp\largefile.mp4");
    }

}
```

Can you show me how you setup your host instance and probably provide some offending test file to me?

**Comment by havokentity** [comment] 2022-10-12 09:45
Hey! 

It stopped happening with the Unity application (Happened just once), but it happens always with Edge Browser. Though I don't need it to work with Edge so for me this is fine. Also even after the exception, server runs fine.

Here's my setup code. ResourceMethod stuff is exactly the same as your example.
```
internal class Program
    {
        static void Main(string[] args)
        {
            ushort port = 60907;
            
            Console.WriteLine($"Starting server on http://localhost:{port}");
            var server = Host.Create();
            server.Port(port);

            var api = Layout.Create()
                .AddService<APIService>("api")
                .Add(CorsPolicy.Permissive());
                
            server.Handler(api)
                    .Defaults()
                    .Development()
                    .Console()
                    .Start(); 
            Console.ReadKey();
            Console.WriteLine("Stopped. Good bye!");
        }
    }
```

I've zipped and attached an offending file.
[Uploading ANIME_DESCRIPTION.zip…]()

**Comment by Kaliumhexacyanoferrat** [comment] 2022-10-12 10:06
Hm, still cannot reproduce this with your bootstrapper. May I ask which operating system (and version) and .NET version you are using?

**Comment by havokentity** [comment] 2022-10-12 10:12
I am using Windows 10 Pro, Version 21H2, OS Build 19044.2006, 
Experience: Windows Feature Experience Pack 120.2212.4180.0.

.NET target framework is net6.0, language version C# 10

(I hope that's what you mean by .NET version)

**Comment by havokentity** [comment] 2022-10-12 10:14
![image](https://user-images.githubusercontent.com/1956037/195316395-4a9048b5-229d-49ba-82f3-66f5fe70573b.png)
Here's a list of "classic" .NET Versions in my PC. Will try to get the non classic .NET versions soon

**Comment by Kaliumhexacyanoferrat** [comment] 2022-12-15 11:22
I am still not able to reproduce this behavior. In the sense of backlog grooming I am closing here - feel free to re-open as soon there is new information.

**Closed by Kaliumhexacyanoferrat** 2022-12-15 11:22 UTC
Labels: question
